version: '3'
services: 
    test-python-socketio:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: test-python-socketio
        depends_on:
            - test-redis-for-socketio
        # links:
        #     - test-redis-for-socketio:test-redis-for-socketio
        volumes: 
            - .:/opt
        command: python3 main.py
        ports: 
            - "5000:5000"
        networks: # 网络配置
            - docker_public_network
        logging: # 日志配置
            driver: "json-file"
            options: 
                max-size: "100m"    # 单个日志文件容量
                max-file: "2"   # 最多多少个日志文件
        deploy: # docker-compose --compatibility up -d
            resources:
                limits:
                    cpus: "1"
                    memory: "30M"


    test-redis-for-socketio:
        image: redis:5
        container_name: test-redis-for-socketio
        expose:
            - "6379"
        ports:
          - "6389:6379"
        networks: # 网络配置
            - docker_public_network
        logging: # 日志配置
            driver: "json-file"
            options: 
                max-size: "100m"    # 单个日志文件容量
                max-file: "2"   # 最多多少个日志文件

    # test-push:
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: test-push
    #     volumes: 
    #         - .:/opt
    #     command: python3 _test_push.py
    #     depends_on:
    #         - test-redis-for-socketio
    #     # links:
    #     #     - test-redis-for-socketio:test-redis-for-socketio
    #     networks: # 网络配置
    #         - docker_public_network
    #     logging: # 日志配置
    #         driver: "json-file"
    #         options: 
    #             max-size: "100m"    # 单个日志文件容量
    #             max-file: "2"   # 最多多少个日志文件

networks: # 网络配置
    docker_public_network:  # 公共网络创建命令: docker network create --subnet=192.111.0.0/16 --gateway=192.111.0.1 docker_public_network
        external: true
